#version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required
volumes:
  db-data:

networks:
  front-tier:
  back-tier:

services:
  vote:
    image: linuxdima/vote:latest
    command: python app.py
    environment:
      REDIS_HOST: "172.31.37.14"
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: linuxdima/result:latest
    command: nodemon server.js
    environment:
      DB_HOST: "172.31.37.14"
      DB_USER: "postgres"
      DB_PSWD: "postgres"
      DB_NAME: "postgres"
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    image: linuxdima/worker:latest   
    environment:
      REDIS_HOST: "172.31.37.14"
      DB_HOST: "172.31.37.14"
      DB_USER: "postgres"
      DB_PSWD: "postgres"
      DB_NAME: "postgres"
    networks:
      - back-tier
